apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
        image: fabricioveronez/pagina-exemplo:blue
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webpage
spec:
  selector:
    app: webpage
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: webpage2
spec:
  selector:
    app: webpage
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
  ---
apiVersion: v1
kind: Service
metadata:
  name: webpage3
spec:
  selector:
    app: webpage
  ports:
  - port: 80
    targetPort: 80
  type: NodePort